language: php

php:
    - 7.0

services:
    - mysql

addons:
    code_climate:
        repo_token: $CODECLIMATE_REPO_TOKEN

before_script:
    - mkdir -p var/jwt
    - openssl genrsa -passout pass:1111 -out var/jwt/private.pem -aes256 4096
    - openssl rsa -passin pass:1111 -pubout -in var/jwt/private.pem -out var/jwt/public.pem
    - cp app/config/parameters_travis.yml app/config/parameters.yml
    - composer install
    - composer require --dev codeclimate/php-test-reporter
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:migrations:migrate --no-interaction --env=test

script:
    - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
    - vendor/bin/test-reporter