language: php

php:
    - 7.0

services:
    - mysql

before_script:
    - mkdir -p var/jwt
    - openssl genrsa -passout pass:1111 -out var/jwt/private.pem -aes256 4096
    - openssl rsa -passin pass:1111 -pubout -in var/jwt/private.pem -out var/jwt/public.pem
    - cp app/config/parameters_travis.yml app/config/parameters.yml
    - composer install
    - bin/console doctrine:database:create --env=test
    - bin/console doctrine:migrations:migrate --no-interaction --env=test

script:
    - vendor/phpunit/phpunit/phpunit --configuration phpunit.xml