parameters:
    database_host: 127.0.0.1
    database_port: ~
    database_name: assistant
    database_user: root
    database_password: ~
    secret: ThisTokenIsNotSoSecretChangeIt
    jwt_key_pass_phrase: 1111
