services:
    app.data_fixtures.faker.provider.abstract_provider:
        abstract: true
        public: false

    app.data_fixtures.faker.provider.period_provider:
        parent: app.data_fixtures.faker.provider.abstract_provider
        class: AppBundle\DataFixtures\Faker\Provider\PeriodProvider
        tags:
            - { name: hautelook_alice.faker.provider }

    app.data_fixtures.faker.provider.user_provider:
        parent: app.data_fixtures.faker.provider.abstract_provider
        class: AppBundle\DataFixtures\Faker\Provider\UserProvider
        arguments: ['@security.password_encoder']
        tags:
            - { name: hautelook_alice.faker.provider }

    app.form.type.user_form_type:
        class: AppBundle\Form\Type\TaskFormType
        tags:
            - { name: form.type }

    app.form.type.task_form_type:
        class: AppBundle\Form\Type\TaskFormType
        tags:
            - { name: form.type }

    app.form.type.task_period_form_type:
        class: AppBundle\Form\Type\TaskPeriodFormType
        tags:
            - { name: form.type }

    app.manager.abstract_manager:
        abstract: true
        class: AppBundle\Manager\AbstractManager
        arguments: ['@doctrine.orm.entity_manager']

    app.manager.task_manager:
        parent: app.manager.abstract_manager
        class: AppBundle\Manager\TaskManager

    app.manager.period_manager:
        parent: app.manager.abstract_manager
        class: AppBundle\Manager\PeriodManager

    app.manager.user_manager:
        parent: app.manager.abstract_manager
        class: AppBundle\Manager\UserManager
        calls:
            - [ setUserPasswordEncoder, [ '@security.password_encoder' ] ]