users:
    type: rest
    resource: '@AppBundle/Controller/UserController.php'
    name_prefix: api_

tasks:
    type: rest
    resource: '@AppBundle/Controller/TaskController.php'
    name_prefix: api_

task_periods:
    type: rest
    resource: '@AppBundle/Controller/TaskPeriodController.php'
    parent: tasks
    name_prefix: api_

periods:
    type: rest
    resource: '@AppBundle/Controller/PeriodController.php'
    name_prefix: api_
