AppBundle\EntityCollection\UserTaskCollection:
    exclusion_policy: ALL
    properties:
        entities:
            expose: true
            type: array<AppBundle\Entity\Task>
        offset:
            expose: true
            type: integer
        limit:
            expose: true
            type: integer
    relations:
        -
            rel: self
            href:
                route: api_get_user_tasks
                parameters:
                    user: expr(object.getUser().getId().toString())
                absolute: true
        -
            rel: entity
            href:
                route: api_get_task
                absolute: true
                generator: templated_uri
                parameters:
                    task: '{id}'
            attributes:
                templated: true
