AppBundle\EntityCollection\UserCategoryCollection:
    exclusion_policy: ALL
    properties:
        entities:
            expose: true
            type: array<AppBundle\Entity\Category>
    relations:
        -
            rel: self
            href:
                route: api_get_user_categories
                parameters:
                    id: expr(object.getUser().getId().toString())
        -
            rel: entity
            href:
                route: api_get_category
                generator: templated_uri
                parameters:
                    id: '{id}'
            attributes:
                templated: true
