AppBundle\EntityCollection\TaskPeriodCollection:
    exclusion_policy: ALL
    properties:
        entities:
            expose: true
            type: array<AppBundle\Entity\Period>
    relations:
        -
            rel: self
            href:
                route: api_get_task_periods
                absolute: true
                generator: templated_uri
                parameters:
                    task: expr(object.getTask().getId().toString())
        -
            rel: entity
            href:
                route: api_get_period
                absolute: true
                generator: templated_uri
                parameters:
                    period: '{id}'
            attributes:
                templated: true
