AppBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        id:
            type: string
        username: ~
        createdAt: ~
    relations:
        -
            rel: self
            href:
                route: api_get_user
                parameters:
                    user: expr(object.getId())
                absolute: true
        -
            rel: tasks
            href:
                route: api_get_tasks
                absolute: true
            embed:
                content: expr(object.getTasks())
