AppBundle\Entity\Category:
    exclusion_policy: ALL
    properties:
        id:
            type: string
        name: ~
        description: ~
        rate: ~
        userId: expr(object.user.getId().toString())
    relations:
        -
            rel: self
            href:
                route: api_get_category
                parameters:
                    id: expr(object.getId())
        -
            rel: tasks
            href:
                route: api_get_category_tasks
                parameters:
                    id: expr(object.getId())
            embed:
                content: expr(object.getTasks())
